sonar.projectKey=account-service
sonar.projectName=account-service
sonar.sources=services/account-service/src
sonar.exclusions=**/node_modules/**,node_modules/**,**/*.test.js,**/coverage/**,**/*.html
#sonar.coverage.exclusions=**/*
#sonar.cpd.exclusions=**/*
#sonar.issue.ignore.multicriteria=e1
#sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S7785
#sonar.issue.ignore.multicriteria.e1.resourceKey=services/account-service/src/index.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
